package com.mapflow.geo.common.model.entities;

// Generated 14-Dec-2011 16:58:39 by Hibernate Tools 3.2.1.GA

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MfServiceLogId generated by hbm2java
 */
@Embeddable
public class MfServiceLogId implements java.io.Serializable {

  private static final long serialVersionUID = -1354408095266478208L;

  private String transactionId;
  private String serviceHost;
  private String serviceName;
  private String clientIp;
  private String clientHostname;
  private Date requestDate;
  private BigDecimal duration;
  private String userField0;
  private String userField1;
  private String userField2;
  private String userField3;
  private String userField4;
  private String userField5;
  private String userField6;
  private String userField7;
  private String userField8;
  private String userField9;
  private String ticket;

  public MfServiceLogId() {
  }

  public MfServiceLogId(final String transactionId, final String serviceHost,
    final String serviceName, final String clientIp, final String clientHostname,
    final Date requestDate, final BigDecimal duration, final String userField0,
    final String userField1, final String userField2, final String userField3,
    final String userField4, final String userField5, final String userField6,
    final String userField7, final String userField8, final String userField9, final String ticket) {
    this.transactionId = transactionId;
    this.serviceHost = serviceHost;
    this.serviceName = serviceName;
    this.clientIp = clientIp;
    this.clientHostname = clientHostname;
    this.requestDate = requestDate;
    this.duration = duration;
    this.userField0 = userField0;
    this.userField1 = userField1;
    this.userField2 = userField2;
    this.userField3 = userField3;
    this.userField4 = userField4;
    this.userField5 = userField5;
    this.userField6 = userField6;
    this.userField7 = userField7;
    this.userField8 = userField8;
    this.userField9 = userField9;
    this.ticket = ticket;
  }

  @Override
  public boolean equals(final Object other) {
    if ((this == other)) {
      return true;
    }
    if ((other == null)) {
      return false;
    }
    if (!(other instanceof MfServiceLogId)) {
      return false;
    }
    final MfServiceLogId castOther = (MfServiceLogId) other;

    return ((this.getTransactionId() == castOther.getTransactionId()) || ((this.getTransactionId() != null)
      && (castOther.getTransactionId() != null) && this.getTransactionId().equals(
      castOther.getTransactionId())))
      && ((this.getServiceHost() == castOther.getServiceHost()) || ((this.getServiceHost() != null)
        && (castOther.getServiceHost() != null) && this.getServiceHost().equals(
        castOther.getServiceHost())))
      && ((this.getServiceName() == castOther.getServiceName()) || ((this.getServiceName() != null)
        && (castOther.getServiceName() != null) && this.getServiceName().equals(
        castOther.getServiceName())))
      && ((this.getClientIp() == castOther.getClientIp()) || ((this.getClientIp() != null)
        && (castOther.getClientIp() != null) && this.getClientIp().equals(castOther.getClientIp())))
      && ((this.getClientHostname() == castOther.getClientHostname()) || ((this.getClientHostname() != null)
        && (castOther.getClientHostname() != null) && this.getClientHostname().equals(
        castOther.getClientHostname())))
      && ((this.getRequestDate() == castOther.getRequestDate()) || ((this.getRequestDate() != null)
        && (castOther.getRequestDate() != null) && this.getRequestDate().equals(
        castOther.getRequestDate())))
      && ((this.getDuration() == castOther.getDuration()) || ((this.getDuration() != null)
        && (castOther.getDuration() != null) && this.getDuration().equals(castOther.getDuration())))
      && ((this.getUserField0() == castOther.getUserField0()) || ((this.getUserField0() != null)
        && (castOther.getUserField0() != null) && this.getUserField0().equals(
        castOther.getUserField0())))
      && ((this.getUserField1() == castOther.getUserField1()) || ((this.getUserField1() != null)
        && (castOther.getUserField1() != null) && this.getUserField1().equals(
        castOther.getUserField1())))
      && ((this.getUserField2() == castOther.getUserField2()) || ((this.getUserField2() != null)
        && (castOther.getUserField2() != null) && this.getUserField2().equals(
        castOther.getUserField2())))
      && ((this.getUserField3() == castOther.getUserField3()) || ((this.getUserField3() != null)
        && (castOther.getUserField3() != null) && this.getUserField3().equals(
        castOther.getUserField3())))
      && ((this.getUserField4() == castOther.getUserField4()) || ((this.getUserField4() != null)
        && (castOther.getUserField4() != null) && this.getUserField4().equals(
        castOther.getUserField4())))
      && ((this.getUserField5() == castOther.getUserField5()) || ((this.getUserField5() != null)
        && (castOther.getUserField5() != null) && this.getUserField5().equals(
        castOther.getUserField5())))
      && ((this.getUserField6() == castOther.getUserField6()) || ((this.getUserField6() != null)
        && (castOther.getUserField6() != null) && this.getUserField6().equals(
        castOther.getUserField6())))
      && ((this.getUserField7() == castOther.getUserField7()) || ((this.getUserField7() != null)
        && (castOther.getUserField7() != null) && this.getUserField7().equals(
        castOther.getUserField7())))
      && ((this.getUserField8() == castOther.getUserField8()) || ((this.getUserField8() != null)
        && (castOther.getUserField8() != null) && this.getUserField8().equals(
        castOther.getUserField8())))
      && ((this.getUserField9() == castOther.getUserField9()) || ((this.getUserField9() != null)
        && (castOther.getUserField9() != null) && this.getUserField9().equals(
        castOther.getUserField9())))
      && ((this.getTicket() == castOther.getTicket()) || ((this.getTicket() != null)
        && (castOther.getTicket() != null) && this.getTicket().equals(castOther.getTicket())));
  }

  @Column(name = "CLIENT_HOSTNAME", length = 50)
  public String getClientHostname() {
    return clientHostname;
  }

  @Column(name = "CLIENT_IP", length = 50)
  public String getClientIp() {
    return clientIp;
  }

  @Column(name = "DURATION", precision = 22, scale = 0)
  public BigDecimal getDuration() {
    return duration;
  }

  @Column(name = "REQUEST_DATE", length = 7)
  public Date getRequestDate() {
    return requestDate;
  }

  @Column(name = "SERVICE_HOST", length = 50)
  public String getServiceHost() {
    return serviceHost;
  }

  @Column(name = "SERVICE_NAME", length = 50)
  public String getServiceName() {
    return serviceName;
  }

  @Column(name = "TICKET", length = 100)
  public String getTicket() {
    return ticket;
  }

  @Column(name = "TRANSACTION_ID", length = 50)
  public String getTransactionId() {
    return transactionId;
  }

  @Column(name = "USER_FIELD_0", length = 50)
  public String getUserField0() {
    return userField0;
  }

  @Column(name = "USER_FIELD_1", length = 50)
  public String getUserField1() {
    return userField1;
  }

  @Column(name = "USER_FIELD_2", length = 50)
  public String getUserField2() {
    return userField2;
  }

  @Column(name = "USER_FIELD_3", length = 50)
  public String getUserField3() {
    return userField3;
  }

  @Column(name = "USER_FIELD_4", length = 50)
  public String getUserField4() {
    return userField4;
  }

  @Column(name = "USER_FIELD_5", length = 50)
  public String getUserField5() {
    return userField5;
  }

  @Column(name = "USER_FIELD_6", length = 50)
  public String getUserField6() {
    return userField6;
  }

  @Column(name = "USER_FIELD_7", length = 50)
  public String getUserField7() {
    return userField7;
  }

  @Column(name = "USER_FIELD_8", length = 50)
  public String getUserField8() {
    return userField8;
  }

  @Column(name = "USER_FIELD_9", length = 50)
  public String getUserField9() {
    return userField9;
  }

  @Override
  public int hashCode() {
    int result = 17;

    result = (37 * result) + (getTransactionId() == null ? 0 : this.getTransactionId().hashCode());
    result = (37 * result) + (getServiceHost() == null ? 0 : this.getServiceHost().hashCode());
    result = (37 * result) + (getServiceName() == null ? 0 : this.getServiceName().hashCode());
    result = (37 * result) + (getClientIp() == null ? 0 : this.getClientIp().hashCode());
    result =
      (37 * result) + (getClientHostname() == null ? 0 : this.getClientHostname().hashCode());
    result = (37 * result) + (getRequestDate() == null ? 0 : this.getRequestDate().hashCode());
    result = (37 * result) + (getDuration() == null ? 0 : this.getDuration().hashCode());
    result = (37 * result) + (getUserField0() == null ? 0 : this.getUserField0().hashCode());
    result = (37 * result) + (getUserField1() == null ? 0 : this.getUserField1().hashCode());
    result = (37 * result) + (getUserField2() == null ? 0 : this.getUserField2().hashCode());
    result = (37 * result) + (getUserField3() == null ? 0 : this.getUserField3().hashCode());
    result = (37 * result) + (getUserField4() == null ? 0 : this.getUserField4().hashCode());
    result = (37 * result) + (getUserField5() == null ? 0 : this.getUserField5().hashCode());
    result = (37 * result) + (getUserField6() == null ? 0 : this.getUserField6().hashCode());
    result = (37 * result) + (getUserField7() == null ? 0 : this.getUserField7().hashCode());
    result = (37 * result) + (getUserField8() == null ? 0 : this.getUserField8().hashCode());
    result = (37 * result) + (getUserField9() == null ? 0 : this.getUserField9().hashCode());
    result = (37 * result) + (getTicket() == null ? 0 : this.getTicket().hashCode());
    return result;
  }

  public void setClientHostname(final String clientHostname) {
    this.clientHostname = clientHostname;
  }

  public void setClientIp(final String clientIp) {
    this.clientIp = clientIp;
  }

  public void setDuration(final BigDecimal duration) {
    this.duration = duration;
  }

  public void setRequestDate(final Date requestDate) {
    this.requestDate = requestDate;
  }

  public void setServiceHost(final String serviceHost) {
    this.serviceHost = serviceHost;
  }

  public void setServiceName(final String serviceName) {
    this.serviceName = serviceName;
  }

  public void setTicket(final String ticket) {
    this.ticket = ticket;
  }

  public void setTransactionId(final String transactionId) {
    this.transactionId = transactionId;
  }

  public void setUserField0(final String userField0) {
    this.userField0 = userField0;
  }

  public void setUserField1(final String userField1) {
    this.userField1 = userField1;
  }

  public void setUserField2(final String userField2) {
    this.userField2 = userField2;
  }

  public void setUserField3(final String userField3) {
    this.userField3 = userField3;
  }

  public void setUserField4(final String userField4) {
    this.userField4 = userField4;
  }

  public void setUserField5(final String userField5) {
    this.userField5 = userField5;
  }

  public void setUserField6(final String userField6) {
    this.userField6 = userField6;
  }

  public void setUserField7(final String userField7) {
    this.userField7 = userField7;
  }

  public void setUserField8(final String userField8) {
    this.userField8 = userField8;
  }

  public void setUserField9(final String userField9) {
    this.userField9 = userField9;
  }

}
