package com.mapflow.geo.common.model.entities;

// Generated 14-Dec-2011 16:58:39 by Hibernate Tools 3.2.1.GA

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * MfServiceLog generated by hbm2java
 */
@Entity
@Table(name = "MF_SERVICE_LOG")
public class MfServiceLog implements java.io.Serializable {

  private static final long serialVersionUID = -8412760885854973013L;
  private MfServiceLogId id;

  public MfServiceLog() {
  }

  public MfServiceLog(final MfServiceLogId id) {
    this.id = id;
  }

  @EmbeddedId
  @AttributeOverrides({
    @AttributeOverride(name = "transactionId", column = @Column(name = "TRANSACTION_ID", length = 50)),
    @AttributeOverride(name = "serviceHost", column = @Column(name = "SERVICE_HOST", length = 50)),
    @AttributeOverride(name = "serviceName", column = @Column(name = "SERVICE_NAME", length = 50)),
    @AttributeOverride(name = "clientIp", column = @Column(name = "CLIENT_IP", length = 50)),
    @AttributeOverride(name = "clientHostname", column = @Column(name = "CLIENT_HOSTNAME", length = 50)),
    @AttributeOverride(name = "requestDate", column = @Column(name = "REQUEST_DATE", length = 7)),
    @AttributeOverride(name = "duration", column = @Column(name = "DURATION", precision = 22, scale = 0)),
    @AttributeOverride(name = "userField0", column = @Column(name = "USER_FIELD_0", length = 50)),
    @AttributeOverride(name = "userField1", column = @Column(name = "USER_FIELD_1", length = 50)),
    @AttributeOverride(name = "userField2", column = @Column(name = "USER_FIELD_2", length = 50)),
    @AttributeOverride(name = "userField3", column = @Column(name = "USER_FIELD_3", length = 50)),
    @AttributeOverride(name = "userField4", column = @Column(name = "USER_FIELD_4", length = 50)),
    @AttributeOverride(name = "userField5", column = @Column(name = "USER_FIELD_5", length = 50)),
    @AttributeOverride(name = "userField6", column = @Column(name = "USER_FIELD_6", length = 50)),
    @AttributeOverride(name = "userField7", column = @Column(name = "USER_FIELD_7", length = 50)),
    @AttributeOverride(name = "userField8", column = @Column(name = "USER_FIELD_8", length = 50)),
    @AttributeOverride(name = "userField9", column = @Column(name = "USER_FIELD_9", length = 50)),
    @AttributeOverride(name = "ticket", column = @Column(name = "TICKET", length = 100)) })
  public MfServiceLogId getId() {
    return id;
  }

  public void setId(final MfServiceLogId id) {
    this.id = id;
  }

}
